from enum import Enum
from typing import Literal


class ActivityType(Enum):
    DEPOSIT = "deposit"
    WITHDRAW = "withdraw"


EVENT_TYPE_LITERAL = Literal["deposit", "withdrawal"]


# Codes:
CODE_EXCESSIVE_WITHDRAWAL_AMOUNT = 1100
CODE_CONSECUTIVE_WITHDRAWALS = 30
CODE_CONSECUTIVE_INCREASING_DEPOSITS = 300
CODE_EXCESSIVE_DEPOSIT_AMOUNT_IN_PERIOD = 123

# Code Expectations:
EXCESSIVE_WITHDRAWAL_AMOUNT = 100
CONSECUTIVE_WITHDRAWALS = 3
CONSECUTIVE_INCREASING_DEPOSITS = 3
EXCESSIVE_DEPOSIT_AMOUNT = 200
EXCESSIVE_DEPOSIT_PERIOD_SECONDS = 30

